"""Hardcoded Kochi Metro stations, ordered from Aluva to Thripunithura."""

STATIONS = [
    {"name": "Aluva", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Pulinchodu", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Companypady", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Ambattukavu", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Muttom", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Kalamassery", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Cochin University", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Pathadipalam", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Edappally", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Changampuzha Park", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Palarivattom", "has_elevator": True, "elevator_status": "Working"},
    {"name": "JLN Stadium", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Kaloor", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Lissie", "has_elevator": True, "elevator_status": "Working"},
    {"name": "MG Road", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Maharaja's College", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Ernakulam South", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Kadavanthra", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Elamkulam", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Vyttila", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Thaikoodam", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Petta", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Vadakkekotta", "has_elevator": True, "elevator_status": "Working"},
    {"name": "SN Junction", "has_elevator": True, "elevator_status": "Working"},
    {"name": "Thripunithura", "has_elevator": True, "elevator_status": "Working"},
]
